// Hero (class) definitions. Weapons are hitscan; damage falls off with range.

export const HEROES = {
  ranger: {
    id: 'ranger',
    name: 'RANGER',
    role: 'Assault',
    color: 0x4ade80,
    hp: 150,
    speed: 6.3,
    blurb: 'Balanced automatic rifle. Good at every range, master of none.',
    weapon: {
      name: 'AR-15 PULSE',
      kind: 'auto',
      damage: 21,
      headMult: 2.0,
      pellets: 1,
      interval: 95,
      mag: 30,
      reload: 1900,
      spread: 0.011,
      spreadPerShot: 0.0055,
      spreadMax: 0.055,
      recoil: 0.9,
      range: 110,
      falloffStart: 32,
      falloffEnd: 85,
      falloffMin: 0.55,
      zoomFov: 55,
    },
    ability: {
      name: 'SURGE',
      key: 'Q',
      cooldown: 9000,
      duration: 4000,
      desc: '+28% move speed and faster reloads.',
    },
  },
  sentinel: {
    id: 'sentinel',
    name: 'SENTINEL',
    role: 'Tank',
    color: 0xfacc15,
    hp: 260,
    speed: 5.2,
    blurb: 'Slow bruiser with a devastating close-range shotgun.',
    weapon: {
      name: 'BREACHER-12',
      kind: 'semi',
      damage: 12,
      headMult: 1.5,
      pellets: 9,
      interval: 780,
      mag: 6,
      reload: 2500,
      spread: 0.05,
      spreadPerShot: 0,
      spreadMax: 0.05,
      recoil: 2.6,
      range: 32,
      falloffStart: 6,
      falloffEnd: 22,
      falloffMin: 0.18,
      zoomFov: 65,
    },
    ability: {
      name: 'BULWARK',
      key: 'Q',
      cooldown: 13000,
      duration: 5000,
      desc: 'Absorb 55% of incoming damage for 5s.',
    },
  },
  marksman: {
    id: 'marksman',
    name: 'MARKSMAN',
    role: 'Sniper',
    color: 0xa78bfa,
    hp: 130,
    speed: 5.9,
    blurb: 'One scoped shot to the head ends most duels.',
    weapon: {
      name: 'LONGVIEW .338',
      kind: 'bolt',
      damage: 92,
      headMult: 2.2,
      pellets: 1,
      interval: 1150,
      mag: 5,
      reload: 2700,
      spread: 0.028,
      zoomSpread: 0,
      spreadPerShot: 0.02,
      spreadMax: 0.09,
      recoil: 3.4,
      range: 240,
      falloffStart: 240,
      falloffEnd: 260,
      falloffMin: 0.9,
      zoomFov: 22,
      scope: true,
    },
    ability: {
      name: 'RECON',
      key: 'Q',
      cooldown: 15000,
      duration: 5000,
      desc: 'Reveal every enemy through walls for your team.',
      team: true,
    },
  },
  medic: {
    id: 'medic',
    name: 'MEDIC',
    role: 'Support',
    color: 0x22d3ee,
    hp: 160,
    speed: 6.5,
    blurb: 'Fast SMG skirmisher that keeps the team standing.',
    weapon: {
      name: 'VESPER SMG',
      kind: 'auto',
      damage: 13,
      headMult: 1.7,
      pellets: 1,
      interval: 68,
      mag: 40,
      reload: 1750,
      spread: 0.017,
      spreadPerShot: 0.005,
      spreadMax: 0.07,
      recoil: 0.6,
      range: 70,
      falloffStart: 16,
      falloffEnd: 50,
      falloffMin: 0.4,
      zoomFov: 60,
    },
    ability: {
      name: 'MEND PULSE',
      key: 'Q',
      cooldown: 11000,
      duration: 0,
      radius: 9,
      heal: 90,
      desc: 'Instantly heal yourself and nearby allies for 90.',
    },
  },
};

export const HERO_IDS = Object.keys(HEROES);

export function getHero(id) {
  return HEROES[id] || HEROES.ranger;
}

/** Damage multiplier for a hitscan weapon at a given distance. */
export function rangeFalloff(weapon, distance) {
  if (distance <= weapon.falloffStart) return 1;
  if (distance >= weapon.falloffEnd) return weapon.falloffMin;
  const t = (distance - weapon.falloffStart) / (weapon.falloffEnd - weapon.falloffStart);
  return 1 + (weapon.falloffMin - 1) * t;
}
